version: '3.9'

services:
  db:
    image: postgres:16
    ports:
      - "127.0.0.43:5433:5432"
    environment: &db_envs
      POSTGRES_DB: int
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: 12345
    volumes:
      - database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - db

  app:
    build: .
    ports:
      - "8189:8189"
    depends_on:
      - db
    environment:
      <<: *db_envs
      POSTGRES_URL: jdbc:postgresql://db:5432/int
      SPRING_PROFILES_ACTIVE: docker
volumes:
  database:
