spring:
  jpa:
    show-sql: true
  datasource:
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:12345}
    url: ${POSTGRES_URL:"jdbc:postgresql://localhost:5432/int"}  

server:
  port: 8189
  servlet:
    context-path: /api

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 1000m
